// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjKCjyTAnQwiq5LJ-Se-csfJe-ljw7Qg4',
    appId: '1:808671027297:web:71b5348b0d410fd1738a20',
    messagingSenderId: '808671027297',
    projectId: 'budget-calculator-1996',
    authDomain: 'budget-calculator-1996.firebaseapp.com',
    storageBucket: 'budget-calculator-1996.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDztI4_Rl8G8kxRvC46AibAzYs9TgxcmZQ',
    appId: '1:808671027297:android:8336489382263542738a20',
    messagingSenderId: '808671027297',
    projectId: 'budget-calculator-1996',
    storageBucket: 'budget-calculator-1996.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApLDmAoBuW7erUv4-4vkU1bOwVhTcppVE',
    appId: '1:808671027297:ios:7f148aa8baae1ad1738a20',
    messagingSenderId: '808671027297',
    projectId: 'budget-calculator-1996',
    storageBucket: 'budget-calculator-1996.firebasestorage.app',
    iosBundleId: 'com.example.bugetCalculator',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApLDmAoBuW7erUv4-4vkU1bOwVhTcppVE',
    appId: '1:808671027297:ios:7f148aa8baae1ad1738a20',
    messagingSenderId: '808671027297',
    projectId: 'budget-calculator-1996',
    storageBucket: 'budget-calculator-1996.firebasestorage.app',
    iosBundleId: 'com.example.bugetCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjKCjyTAnQwiq5LJ-Se-csfJe-ljw7Qg4',
    appId: '1:808671027297:web:fffeda4716debb4f738a20',
    messagingSenderId: '808671027297',
    projectId: 'budget-calculator-1996',
    authDomain: 'budget-calculator-1996.firebaseapp.com',
    storageBucket: 'budget-calculator-1996.firebasestorage.app',
  );
}
